name: Swizzle Sticks
favicon: null
layout_spectrum: 0.2429809276945889
typography_spectrum: 0.7231921846978366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e4df'
    - '#bdbcb7'
    - '#1f1f21'
    - '#7a7267'
    - '#792827'
  brandStrength: 0.9242302663624287
  lightness: 0.5623827623203397
  saturation: 0.5896103638224304
  rhythmicContrast: 0.9104623110033572
purpose: []
